export const CREDENTIAL_ROTATION_HANDOFF_STATUSES = [
  "blocked_by_incident_record",
  "ready_for_owner_rotation",
  "rotation_contained"
];

export function buildCredentialRotationHandoff(input = {}, options = {}) {
  const generatedAt = options.generatedAt || new Date().toISOString();
  const actionPack = plainObject(input.actionPack);
  const paths = normalizePaths(input.paths || {});
  const actions = actionSummaries(actionPack.actions);
  const actionPackReady = actionPack.valid === true;
  const rotationContained = actionPack.status === "no_rotation_needed" || (actionPack.incidentStatus === "contained" && actions.length === 0);
  const blockers = blockersFor({ actionPack, actionPackReady, rotationContained, sourceErrors: input.sourceErrors });
  const incidentGaps = rotationContained
    ? []
    : (Array.isArray(actionPack.incidentBlockers) ? actionPack.incidentBlockers.map((reason) => `secret exposure incident: ${reason}`) : []);
  const commands = commandSet(paths);
  const acceptanceCriteria = [
    "Every replacement credential is created and stored outside this repository.",
    "Funds are moved by the wallet owner to a fresh wallet before the exposed wallet is retired.",
    "The exposed X/API token is revoked or regenerated by the account owner before any posting approval.",
    "The incident record contains only redacted proof references and ISO-8601 timestamps.",
    "secret-exposure-response, live-resource-handoff, readiness, and operate all run after the redacted update."
  ];
  const warnings = unique([
    ...(Array.isArray(input.sourceWarnings) ? input.sourceWarnings : []),
    ...(Array.isArray(actionPack.warnings) ? actionPack.warnings.map((warning) => `credential rotation action pack: ${warning}`) : [])
  ]);
  const status = rotationContained
    ? "rotation_contained"
    : blockers.length === 0 && actions.length > 0
      ? "ready_for_owner_rotation"
      : "blocked_by_incident_record";
  const nextAction = nextActionFor(status, actions, blockers);
  const markdown = buildMarkdown({
    generatedAt,
    status,
    incidentId: actionPack.incidentId,
    incidentStatus: actionPack.incidentStatus,
    exposureCount: actionPack.exposureCount,
    unresolvedCount: actionPack.unresolvedCount,
    actions,
    blockers,
    incidentGaps,
    commands,
    acceptanceCriteria,
    warnings,
    nextAction
  });

  return {
    generatedAt,
    valid: true,
    status,
    incidentId: actionPack.incidentId || null,
    incidentStatus: actionPack.incidentStatus || null,
    exposureCount: numberOrZero(actionPack.exposureCount),
    unresolvedCount: numberOrZero(actionPack.unresolvedCount),
    actionPack: {
      valid: actionPackReady,
      status: actionPack.status || null,
      actionCount: actions.length
    },
    actions,
    blockers,
    incidentGaps,
    commands,
    acceptanceCriteria,
    warnings,
    markdown,
    nextAction,
    evidenceBoundary: {
      readsLocalIncidentMetadata: true,
      writesFiles: false,
      movesFunds: false,
      revokesTokens: false,
      storesSecrets: false,
      storesReplacementCredentials: false,
      postsContent: false,
      sendsOutreach: false,
      signsWalletPayloads: false,
      deploysContracts: false,
      startsRuntime: false,
      startsPilotTraffic: false,
      updatesCanonicalState: false,
      enablesToken: false,
      requiresOwnerAction: true
    }
  };
}

export function publicCredentialRotationHandoffReport(report = {}) {
  return {
    ...report,
    markdown: undefined
  };
}

function blockersFor({ actionPack, actionPackReady, rotationContained, sourceErrors }) {
  if (rotationContained) return [];

  const blockers = [...(Array.isArray(sourceErrors) ? sourceErrors : [])];
  if (!actionPackReady) {
    const reasons = Array.isArray(actionPack.reasons) ? actionPack.reasons : [];
    blockers.push(...(reasons.length ? reasons.map((reason) => `credential rotation action pack: ${reason}`) : ["credential rotation action pack is not ready"]));
  }
  if (!actionPack.incidentId) blockers.push("No secret exposure incident id is selected");
  if (actionPack.status === "unsafe_secret_material") blockers.push("Incident record still contains raw secret-like material");
  if (actionPack.status === "needs_incident_record") blockers.push("Incident record is incomplete or missing");
  return unique(blockers);
}

function commandSet(paths) {
  return {
    actionPack: `npm run credential-rotation-action-pack -- ${paths.incident}`,
    validateIncident: `npm run secret-exposure-response -- ${paths.incident}`,
    liveResourceHandoff: "npm run live-resource-handoff",
    readiness: "npm run readiness",
    operate: "npm run operate"
  };
}

function buildMarkdown({
  generatedAt,
  status,
  incidentId,
  incidentStatus,
  exposureCount,
  unresolvedCount,
  actions,
  blockers,
  incidentGaps,
  commands,
  acceptanceCriteria,
  warnings,
  nextAction
}) {
  const lines = [
    "# Allow Credential Rotation Handoff",
    "",
    `Generated: ${generatedAt}`,
    `Status: ${status}`,
    `Incident: ${incidentId || "not selected"}`,
    `Incident Status: ${incidentStatus || "unknown"}`,
    `Exposures: ${numberOrZero(exposureCount)}`,
    `Unresolved: ${numberOrZero(unresolvedCount)}`,
    "",
    "## Safety Boundary",
    "",
    "- This handoff is local review material only.",
    "- It does not move funds, revoke tokens, store secrets, store replacement credentials, post content, send outreach, sign wallet payloads, deploy contracts, start runtime, start pilot traffic, update canonical state, or enable a token.",
    "- The owner performs rotation in wallet/provider interfaces and records only redacted proof references.",
    ""
  ];

  if (blockers.length > 0) {
    lines.push("## Blockers", "");
    for (const blocker of blockers) lines.push(`- ${blocker}`);
    lines.push("");
  }

  if (incidentGaps.length > 0) {
    lines.push("## Incident Gaps", "");
    for (const gap of incidentGaps) lines.push(`- ${gap}`);
    lines.push("");
  }

  lines.push("## Owner Actions", "");
  if (actions.length === 0) {
    lines.push("No owner rotation actions remain open.", "");
  } else {
    for (const action of actions) {
      lines.push(`### ${action.title}`);
      lines.push("");
      lines.push(`- id: \`${action.actionId}\``);
      lines.push(`- type: \`${action.actionType}\``);
      lines.push(`- mode: \`${action.executionMode}\``);
      for (const step of action.steps) lines.push(`- ${step}`);
      if (Object.keys(action.incidentUpdate).length > 0) {
        lines.push("- redacted incident update:");
        lines.push("```json");
        lines.push(JSON.stringify(action.incidentUpdate, null, 2));
        lines.push("```");
      }
      lines.push("");
    }
  }

  lines.push("## Commands", "");
  for (const [label, command] of Object.entries(commands)) {
    lines.push(`- ${label}: \`${command}\``);
  }
  lines.push("");

  lines.push("## Acceptance Criteria", "");
  for (const item of acceptanceCriteria) lines.push(`- ${item}`);
  lines.push("");

  if (warnings.length > 0) {
    lines.push("## Warnings", "");
    for (const warning of warnings) lines.push(`- ${warning}`);
    lines.push("");
  }

  lines.push("## Next Action", "", nextAction);
  return lines.join("\n");
}

function actionSummaries(value) {
  return Array.isArray(value)
    ? value.map((action) => ({
        actionId: action.actionId || null,
        actionType: action.actionType || null,
        status: action.status || null,
        executionMode: action.executionMode || null,
        title: action.title || "Owner rotation action",
        steps: Array.isArray(action.steps) ? action.steps.filter(Boolean) : [],
        incidentUpdate: plainObject(action.incidentUpdate)
      }))
    : [];
}

function nextActionFor(status, actions, blockers) {
  if (status === "rotation_contained") {
    return "Rerun live-resource handoff and readiness, then prepare the next action-time approval packet with replacement credentials stored outside the repository.";
  }
  if (status === "ready_for_owner_rotation") {
    return `Owner completes ${actions.length} outside-repo rotation action${actions.length === 1 ? "" : "s"}, updates only redacted incident proof fields, then runs the post-rotation commands.`;
  }
  if (blockers.some((blocker) => /raw secret/i.test(blocker))) {
    return "Remove raw secret-like material from the incident record before preparing owner rotation steps.";
  }
  return "Repair the redacted incident record, then regenerate the credential rotation handoff.";
}

function normalizePaths(paths = {}) {
  return {
    incident: paths.incident || "ops/secret_exposure_incident.template.json"
  };
}

function numberOrZero(value) {
  return Number.isFinite(Number(value)) ? Number(value) : 0;
}

function plainObject(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}
